server:
  port: 3333
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/end_point?useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: root
# 邮件
  mail:
    from: coolk1ng@163.com
    protocol: smtps
    host: smtp.163.com
    port: 465
    username: coolk1ng@163.com
    password: xxxxxxx
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
# rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        # 设置消费端手动 ack
        acknowledge-mode: manual
        # 是否支持重试
        retry:
          enabled: true
        prefetch: 1
        auto-startup: true
# redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 1000
    database: 10
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
# mybatis
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.coolk1ng: debug

